// packages/feedback/react/feedback.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import Feedback from '../components/feedback/feedback.js';

export const C4AIFeedback = createComponent({
  tagName: 'c4ai-feedback',
  elementClass: Feedback,
  react: React,
  events: {},
});

// packages/web-components/src/components/feedback/components/feedback/feedback.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities';
import { Feedback } from './src/feedback';
import { TemplateResult } from 'lit';
import { feedbackTemplate } from './src/feedback.template.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Component extending the Feedback component
 *
 * @element clabs-feedback
 */
@customElement(`${clabsPrefix}-feedback`)
class CLABSFeedback extends Feedback {
  /**
   * Renders the template while passing in class functionality
   */
  render(): TemplateResult<1> {
    return feedbackTemplate(this);
  }
}

export default CLABSFeedback;
