// packages/web-components/src/components/example-button/components/example-button/example-button.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities';
import exampleButton from './src/example-button.template.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Component extending the @carbon/web-components' button
 */
@customElement(`${clabsPrefix}-example-button`)
class CLABSExampleButton extends exampleButton {}

export default CLABSExampleButton;

// packages/web-components/src/components/example-button/react/example-button.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import ExampleButton from '../components/example-button/example-button.js';

export const CLABSExampleButton = createComponent({
  tagName: 'clabs-example-button',
  elementClass: ExampleButton,
  react: React,
  events: {},
});
