// packages/react/src/components/ExampleButton/components/ExampleButton.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React from 'react';
import { Button, ButtonProps } from '@carbon/react';
import { usePrefix } from '@carbon-labs/utilities/es/index.js';

/** Primary UI component for user interaction */

interface ExampleButtonProps extends ButtonProps<any> {
  children?: React.ReactNode;
}

export const ExampleButton = ({
  children = 'Button',
  ...rest
}: ExampleButtonProps) => {
  const prefix = usePrefix();

  return (
    <div className={`${prefix}--example-button__container`}>
      <Button {...rest}>{children}</Button>
    </div>
  );
};

// packages/web-components/src/components/example-button/components/example-button/example-button.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities/es/settings/index.js';
import exampleButton from './src/example-button.template.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Component extending the @carbon/web-components' button
 */
@customElement(`${clabsPrefix}-example-button`)
class CLABSExampleButton extends exampleButton {}

export default CLABSExampleButton;
