// packages/react/tasks/generate/templates/components/DISPLAY_NAME.tsx
/**
 * @license
 *
 * Copyright IBM Corp. FULL_YEAR
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React from 'react';
import { Button, ButtonProps } from '@carbon/react';
import { usePrefix } from '@carbon-labs/utilities/es/index.js';

/** Primary UI component for user interaction */

interface DISPLAY_NAMEProps extends ButtonProps<any> {
  children?: React.ReactNode;
}

export const DISPLAY_NAME = ({
  children = 'Button',
  ...rest
}: DISPLAY_NAMEProps) => {
  const prefix = usePrefix();

  return (
    <div className={`${prefix}--STYLE_NAME__container`}>
      <Button {...rest}>{children}</Button>
    </div>
  );
};

// packages/web-components/tasks/generate/templates/components/DISPLAY_NAME/DISPLAY_NAME.ts
/**
 * @license
 *
 * Copyright IBM Corp. FULL_YEAR
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities/es/settings/index.js';
import CAMEL_CASE from './src/DISPLAY_NAME.template.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Component extending the @carbon/web-components' button
 */
@customElement(`${clabsPrefix}-DISPLAY_NAME`)
class CLABSPASCAL_CASE extends CAMEL_CASE {}

export default CLABSPASCAL_CASE;
