// packages/web-components/src/components/style-picker/components/style-picker-sections/style-picker-sections.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { stylePickerSectionsTemplate } from './src/style-picker-sections.template.js';
import { consume } from '@lit/context';
import {
  stylePickerContext,
  type StylePickerContextType,
} from '../../context/style-picker-context.js';
import StylePickerSections from './src/style-picker-sections.js';
import { prefix } from '../../defs/index.js';

/**
 * A wrapper wraps multiple `style-picker-section` components.
 *
 * @elements clabs-style-picker-sections
 */
@customElement(`${prefix}-sections`)
class CLABSStylePickerSections extends StylePickerSections {
  @consume({ context: stylePickerContext, subscribe: true })
  stylePickerContext?: StylePickerContextType;

  /**
   * Renders the template while passing in class functionality
   *
   * @returns {TemplateResult<1>}
   */
  render() {
    return stylePickerSectionsTemplate(this);
  }
}

export default CLABSStylePickerSections;

// packages/web-components/src/components/style-picker/react/style-picker-sections.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import StylePickerSections from '../components/style-picker-sections/style-picker-sections';

export const CLABSStylePickerSections = createComponent({
  tagName: 'clabs-style-picker-sections',
  elementClass: StylePickerSections,
  react: React,
  events: {},
});
