// packages/react/src/components/StylePicker/components/style-picker-color.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { CLABSStylePickerColor } from '@carbon-labs/wc-style-picker/es/index';

export const StylePickerColor = createComponent({
  tagName: 'clabs-style-picker-color',
  elementClass: CLABSStylePickerColor,
  react: React,
  events: {},
});

// packages/web-components/src/components/style-picker/components/style-picker-color/style-picker-color.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities/es/settings/index.js';
import { stylePickerColorTemplate } from './src/style-picker-color.template.js';
import StylePickerColor from './src/style-picker-color.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Color element
 *
 * @element clabs-style-picker-color-module
 */
@customElement(`${clabsPrefix}-style-picker-color`)
class CLABSStylePickerColor extends StylePickerColor {
  /**
   * Renders the template while passing in class functionality
   *
   * @returns {TemplateResult<1>}
   */
  render() {
    return stylePickerColorTemplate(this);
  }
}

export default CLABSStylePickerColor;
