// packages/web-components/src/components/style-picker/react/style-picker-color.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import StylePickerColor from '../components/style-picker-color/style-picker-color.js';

export const CLABSStylePickerColor = createComponent({
  tagName: 'clabs-style-picker-color',
  elementClass: StylePickerColor,
  react: React,
  events: {},
});

// packages/web-components/src/components/style-picker/components/style-picker-color/style-picker-color.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { stylePickerColorTemplate } from './src/style-picker-color.template.js';
import StylePickerColor from './src/style-picker-color.js';
import { prefix } from '../../defs/index.js';

/**
 * Color picker option component extending the StylePickerColor base class.
 *
 * @element clabs-style-picker-color
 */
@customElement(`${prefix}-color`)
class CLABSStylePickerColor extends StylePickerColor {
  /**
   * Renders the template while passing in class functionality
   *
   * @returns {TemplateResult<1>}
   */
  render() {
    return stylePickerColorTemplate(this);
  }
}

export default CLABSStylePickerColor;
