// packages/web-components/src/components/style-picker/components/style-picker-group/src/style-picker-group.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-ignore
import styles from './style-picker-group.scss?inline';
import { LitElement } from 'lit';

/**
 * Group element.
 */
class StylePickerGroup extends LitElement {
  static styles = styles;
}

export default StylePickerGroup;

// packages/react/src/components/StylePicker/components/style-picker-group.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { CLABSStylePickerGroup } from '@carbon-labs/wc-style-picker/es/index';

export const StylePickerGroup = createComponent({
  tagName: 'clabs-style-picker-group',
  elementClass: CLABSStylePickerGroup,
  react: React,
  events: {},
});
