// packages/web-components/src/components/style-picker/components/style-picker/style-picker.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities/es/settings/index.js';
import { stylePickerTemplate } from './src/style-picker.template.js';
import stylePicker from './src/style-picker.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Component extending the @carbon/web-components' button
 */
@customElement(`${clabsPrefix}-style-picker`)
class CLABSStylePicker extends stylePicker {
  /**
   * Renders the template while passing in class functionality
   *
   * @returns {TemplateResult<1>}
   */
  render() {
    return stylePickerTemplate(this);
  }
}

export default CLABSStylePicker;

// packages/react/src/components/StylePicker/components/StylePicker.tsx
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */
import React from 'react';
import { usePrefix } from '@carbon-labs/utilities/es/index.js';
import { CLABSStylePicker as CLABSStylePickerWC } from '../../../../../web-components/src/components/style-picker/react/style-picker';

export const StylePicker = () => {
  const prefix = usePrefix();
  return (
    <div className={`${prefix}--style-picker__container`}>
      <CLABSStylePickerWC />
    </div>
  );
};
