// packages/web-components/src/components/style-picker/components/style-picker-group/style-picker-group.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement } from 'lit/decorators.js';
import { settings } from '@carbon-labs/utilities/es/settings/index.js';
import { stylePickerGroupTemplate } from './src/style-picker-group.template.js';
import StylePickerGroup from './src/style-picker-group.js';

const { stablePrefix: clabsPrefix } = settings;

/**
 * Group wrapper element.
 *
 * @element clabs-style-picker-group
 */
@customElement(`${clabsPrefix}-style-picker-group`)
class CLABSStylePickerGroup extends StylePickerGroup {
  /**
   * Renders the template while passing in class functionality
   *
   * @returns {TemplateResult<1>}
   */
  render() {
    return stylePickerGroupTemplate(this);
  }
}

export default CLABSStylePickerGroup;

// packages/react/src/components/StylePicker/components/style-picker-group.ts
/**
 * @license
 *
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { CLABSStylePickerGroup } from '@carbon-labs/wc-style-picker/es/index';

export const StylePickerGroup = createComponent({
  tagName: 'clabs-style-picker-group',
  elementClass: CLABSStylePickerGroup,
  react: React,
  events: {},
});
